stages:
  - validate
  - build
  - deploy

variables:
  DEPLOY_PATH: "/opt/www"
  SERVICE_NAME: "flask-helpdesk"
  DEPLOY_DOMAIN: "its.tez-tour.com"

# Shell-based CI/CD (без Docker)
validate_shell:
  stage: validate
  tags:
    - shell
  script:
    - echo "🔍 Shell-based валидация проекта..."
    - echo "📁 Текущая директория:"
    - pwd
    - echo "📋 Содержимое проекта:"
    - ls -la
    - echo "🐍 Проверка Python:"
    - python3 --version || python --version || echo "⚠️ Python не найден"
    - echo "✅ Shell валидация завершена"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
  allow_failure: true

build_shell:
  stage: build
  tags:
    - shell
  script:
    - echo "📦 Shell-based сборка пакета..."
    - mkdir -p deployment_package
    - echo "📋 Копируем файлы проекта:"

    # Копируем основные файлы
    - cp app.py deployment_package/ 2>/dev/null && echo "✅ app.py" || echo "⚠️ app.py не найден"
    - cp requirements.txt deployment_package/ 2>/dev/null && echo "✅ requirements.txt" || echo "⚠️ requirements.txt не найден"
    - cp config.ini deployment_package/ 2>/dev/null && echo "✅ config.ini" || echo "⚠️ config.ini не найден"
    - cp *.py deployment_package/ 2>/dev/null && echo "✅ Python файлы" || echo "⚠️ Дополнительные .py файлы не найдены"

    # Копируем директории
    - cp -r blog/ deployment_package/ 2>/dev/null && echo "✅ blog/" || echo "ℹ️ blog/ не найдена"
    - cp -r static/ deployment_package/ 2>/dev/null && echo "✅ static/" || echo "ℹ️ static/ не найдена"
    - cp -r templates/ deployment_package/ 2>/dev/null && echo "✅ templates/" || echo "ℹ️ templates/ не найдена"
    - cp -r migrations/ deployment_package/ 2>/dev/null && echo "✅ migrations/" || echo "ℹ️ migrations/ не найдена"

    # Конфигурационные файлы для сервера
    - cp flask-helpdesk.service.redhat deployment_package/flask-helpdesk.service 2>/dev/null && echo "✅ service файл" || echo "ℹ️ service файл не найден"
    - cp flask-helpdesk.nginx.conf deployment_package/ 2>/dev/null && echo "✅ nginx конфиг" || echo "ℹ️ nginx конфиг не найден"

    # Создаем архив
    - cd deployment_package
    - tar -czf ../deployment_package_shell.tar.gz .
    - cd ..
    - echo "📦 Содержимое пакета:"
    - tar -tvf deployment_package_shell.tar.gz | head -n 20
    - echo "✅ Shell пакет создан:"
    - ls -lh deployment_package_shell.tar.gz
  artifacts:
    paths:
      - deployment_package_shell.tar.gz
      - deployment_package/
    expire_in: 1 day
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

deploy_shell:
  stage: deploy
  tags:
    - shell
  script:
    - echo "🚀 Shell-based деплой на сервер..."
    - |
      if [ -z "$SSH_PRIVATE_KEY" ] || [ -z "$DEPLOY_SERVER" ] || [ -z "$DEPLOY_USER" ]; then
        echo "ℹ️ Переменные деплоя не настроены"
        echo ""
        echo "📋 Необходимые переменные в GitLab CI/CD Settings → Variables:"
        echo "   🔑 SSH_PRIVATE_KEY = приватный SSH ключ (начинается с -----BEGIN)"
        echo "   🌐 DEPLOY_SERVER = 10.7.74.252"
        echo "   👤 DEPLOY_USER = deploy"
        echo ""
        echo "✅ Пакет готов к ручному деплою"
        echo "📦 Файл: deployment_package_shell.tar.gz"
        exit 0
      fi

    - echo "✅ Переменные деплоя найдены"
    - echo "🔐 Настройка SSH..."

    # Проверяем наличие ssh-agent
    - which ssh-agent || echo "⚠️ ssh-agent не найден"
    - eval $(ssh-agent -s) || echo "⚠️ Проблема с ssh-agent"

    # Добавляем SSH ключ
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - || echo "⚠️ Проблема с SSH ключом"

    # Настраиваем SSH
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts 2>/dev/null || echo "⚠️ Проблема с ssh-keyscan"

    - echo "🔍 Проверка подключения..."
    - ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "echo '✅ SSH соединение работает'" || echo "❌ SSH соединение не работает"

    - echo "📁 Передача файлов..."
    - |
      if [ -f "deployment_package_shell.tar.gz" ]; then
        echo "📤 Отправляем архив на сервер..."
        cat deployment_package_shell.tar.gz | ssh -o ConnectTimeout=30 $DEPLOY_USER@$DEPLOY_SERVER "
          cd /opt/www 2>/dev/null || sudo mkdir -p /opt/www
          sudo tar -xzf - 2>/dev/null || echo '⚠️ Проблема с распаковкой архива'
          echo '✅ Файлы переданы в /opt/www'
          echo '📋 Содержимое /opt/www:'
          sudo ls -la /opt/www/ 2>/dev/null || echo '⚠️ Не удалось просмотреть /opt/www'
        "
      else
        echo "❌ Файл deployment_package_shell.tar.gz не найден"
        exit 1
      fi

    - echo "🎉 Shell деплой завершен!"
    - echo ""
    - echo "🔧 Следующие шаги на сервере:"
    - echo "   1. ssh deploy@10.7.74.252"
    - echo "   2. sudo systemctl restart flask-helpdesk"
    - echo "   3. sudo systemctl status flask-helpdesk"
    - echo "   4. curl -I http://its.tez-tour.com"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
  allow_failure: false
