version: '3.8'

services:
  # Flask приложение
  flask-helpdesk:
    build:
      context: .
      dockerfile: Dockerfile.gitlab
    container_name: flask-helpdesk
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=mysql+pymysql://flask_user:flask_password@mysql:3306/flask_helpdesk
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - flask_logs:/app/logs
    depends_on:
      - mysql
      - redis
    networks:
      - flask-network

  # MySQL база данных
  mysql:
    image: mysql:8.0
    container_name: flask-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: flask_helpdesk
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - flask-network

  # Redis для кэширования и сессий
  redis:
    image: redis:7-alpine
    container_name: flask-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - flask-network

  # Nginx для production-like окружения
  nginx:
    image: nginx:alpine
    container_name: flask-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./blog/static:/var/www/static
    depends_on:
      - flask-helpdesk
    networks:
      - flask-network

  # GitLab Runner для локального тестирования CI/CD
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab_runner_config:/etc/gitlab-runner
    networks:
      - flask-network

volumes:
  mysql_data:
  redis_data:
  flask_logs:
  gitlab_runner_config:

networks:
  flask-network:
    driver: bridge
