#!/usr/bin/env python3
"""
Тестовый скрипт для проверки работы CSRF
Запускайте из директории проекта: /opt/www/its.teztour.com/
"""

import os
import sys
import requests
from pathlib import Path

# Добавляем путь к проекту
BASE_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(BASE_DIR))

print("🧪 Тестирование CSRF на странице входа...")

try:
    # Загружаем переменные окружения
    if os.path.exists('.env.production'):
        from dotenv import load_dotenv
        load_dotenv('.env.production')
        print("✅ Загружен .env.production")

    # Создаем тестовый клиент Flask
    from blog import create_app
    app = create_app()

    # Создаем тестовый клиент
    client = app.test_client()

    with app.app_context():
        # Получаем страницу входа
        print("📄 Запрашиваем страницу входа...")
        response = client.get('/login')

        if response.status_code == 200:
            print("✅ Страница входа успешно загружена")

            # Проверяем наличие скрытого поля CSRF (generated by form.hidden_tag())
            if b'name="csrf_token"' in response.data:
                print("✅ Скрытое поле CSRF токена найдено в форме")
            else:
                print("❌ Скрытое поле CSRF токена не найдено в форме")

            # Проверяем наличие тега meta с CSRF токеном
            if b'csrf-token' in response.data:
                print("✅ Meta тег с CSRF токеном найден")
            else:
                print("❌ Meta тег с CSRF токеном не найден")

            # Извлекаем CSRF токен из формы для теста
            import re
            from flask_wtf.csrf import generate_csrf

            # Находим CSRF токен в форме (form.hidden_tag() генерирует скрытое поле)
            csrf_match = re.search(rb'name="csrf_token" type="hidden" value="([^"]+)"', response.data)
            if csrf_match:
                form_csrf_token = csrf_match.group(1).decode('utf-8')
                print(f"🔍 CSRF токен из формы: {form_csrf_token}")
            else:
                # Пробуем другой паттерн для поиска CSRF токена
                csrf_match = re.search(rb'name="csrf_token" value="([^"]+)"', response.data)
                if csrf_match:
                    form_csrf_token = csrf_match.group(1).decode('utf-8')
                    print(f"🔍 CSRF токен из формы (альтернативный поиск): {form_csrf_token}")
                else:
                    print("❌ CSRF токен не найден в форме")
                    # Генерируем токен и вручную добавляем в сессию
                    form_csrf_token = generate_csrf()
                    print(f"🔍 Сгенерированный CSRF токен: {form_csrf_token}")

            # Flask-WTF хранит токены в сессии особым образом
            with client.session_transaction() as sess:
                # Flask-WTF ожидает токен в сессии без кавычек
                sess['csrf_token'] = form_csrf_token
                sess.permanent = True

                print(f"🔍 CSRF токен установлен в сессии: {sess.get('csrf_token')}")

            # Пытаемся отправить форму с правильным токеном
            print("\n📤 Тестируем отправку формы с правильным CSRF токеном...")

            # Для теста используем тот же токен, что и в форме
            response = client.post('/login', data={
                'csrf_token': form_csrf_token,
                'username': 'test',
                'password': 'test',
                'remember': 'y'
            }, follow_redirects=True)

            print(f"🔍 Статус POST запроса: {response.status_code}")
            if b'csrf' in response.data.lower():
                print("❌ Форма отклонена с ошибкой CSRF")
                # Ищем сообщение об ошибке CSRF
                error_match = re.search(rb'CSRF.*?(?:<[^>]*>)', response.data)
                if error_match:
                    print(f"🔍 Ошибка CSRF: {error_match.group(0).decode('utf-8')}")
            else:
                print("✅ Форма принята без ошибки CSRF")

            # Проверяем содержимое ответа для отладки
            print(f"🔍 Содержимое ответа (первые 200 байт): {response.data[:200]}")

            # Пытаемся отправить форму с неправильным токеном
            print("\n📤 Тестируем отправку формы с неправильным CSRF токеном...")
            response = client.post('/login', data={
                'csrf_token': 'wrong_token',
                'username': 'test',
                'password': 'test',
                'remember': 'y'
            }, follow_redirects=True)

            if b'csrf' in response.data.lower() or response.status_code == 400:
                print("✅ Форма правильно отклонена с ошибкой CSRF")
            else:
                print("❌ Форма принята с неправильным CSRF токеном")

        else:
            print(f"❌ Ошибка загрузки страницы входа: {response.status_code}")

    print("\n🎉 Тестирование CSRF завершено!")

except Exception as e:
    print(f"\n❌ Ошибка при тестировании CSRF: {e}")
    import traceback
    traceback.print_exc()
