"""Add easy_email_to field to redmine_notifications

Revision ID: add_easy_email_to_redmine_notifications
Revises: create_redmine_notifications_table
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_easy_email_to_redmine_notifications'
down_revision = 'create_redmine_notifications_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Эта миграция больше не нужна, так как колонка easy_email_to уже включена в create_redmine_notifications_table
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Эта миграция больше не нужна, так как колонка easy_email_to уже включена в create_redmine_notifications_table
    pass
    # ### end Alembic commands ###
