"""empty message

Revision ID: b9d14da31b4c
Revises: 
Create Date: 2021-08-28 15:16:56.658050

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b9d14da31b4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
                    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
                    sa.Column('image_file', sa.VARCHAR(length=20), nullable=False),
                    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
                    sa.Column('last_seen', sa.DATETIME(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    # ### end Alembic commands ###
